export const FILTER_TEXT_CHANGED = 'FILTER_TEXT_CHANGED'
export const FILTER_CATEGORY_SELECTED = "FILTER_CATEGORY_SELECTED"
export const SET_MODAL = "SET_MODAL"
export const TOGGLE_MODAL = "TOGGLE_MODAL"

